### ISSUE TITLE
Minor adjustments to config files

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#129] opened 2016-08-30 07:49 UTC
1. Align the use of chars for separating multiple values in config files, e.g. to "|".

No there is sometimes "|", sometimes " ".

```
kb.predicates=config\\Jan\\enums\\dbpedia.properties|config\\Jan\\enums\\dc.properties|config\\Jan\\enums\\foaf.properties|config\\Jan\\enums\\rdf.properties
```

For particular predicate names: 

```
kb.predicate.name=http://dbpedia.org/property/name http://dbpedia.org/property/fullname
```

**Comment by brodecva** [comment] 2016-08-31 15:29
> Create just one "sample config" folder, under "sti/config/". Right now, there is this sample config and also "sti/config/Jan".

I have already instructed @JanVana  to do so in #131 .

**Comment by brodecva** [comment] 2016-08-31 15:38
> No there is sometimes "|", sometimes " ".

@tomas-knap This is probably caused by the fact, that in the first case, the '|' separates file path fragments (and @JanVana assumes that your OS does not use or you refrain from using "|" in the file path), in the second case ' ' separates two URLs. The '|' could be used instead of ' ', as it is not a valid URL character (but it might confused with '/').

Nevertheless I would postpone such changes until we are clear what parts of configuration will be really left, and what parts become a part of runtime configuration, kept somewhere else than in these configuration files.

**Comment by tomas-knap** [comment] 2016-09-01 08:03
Ok, moved for 3rd iteration (end of the iteration). The goal is to check these kind of inconsistencies in the config file.

**Comment by JanVana** [comment] 2016-09-02 08:51
This is intentional.

Space is used for separating URLs, because URL can never contain space. But pipe is a special character, that can be used in URL.

Pipe is used for separating files, because space can be commonly used in file names. There are many characters on Windows, that can never be in a file path, but there is no such restriction on linux. I have selected the pipe character, because I have never used it in file names myself and there is graphically looks like a separator.

**Comment by brodecva** [comment] 2017-01-13 11:56
> This is intentional.
>
> Space is used for separating URLs, because URL can never contain a space character. But pipe is a special character, that can be used in URL.
>
> Pipe is used for separating files, because space can be commonly used in file names. There are many characters on Windows, that can never be in a file path, but there is no such restriction on linux. I have selected the pipe character, because I have never used it in file names myself and there it graphically looks like a separator.

@JanVana @tomas-knap This seems reasonable to me. Let us close it.

**Closed** 2017-01-13 11:56 UTC
Labels: enhancement, extension, knowledge bases, priority: Low
