### ISSUE TITLE
Exception handling in the core

### ISSUE THREAD

**Issue by JanVana** [odalic/sti#166] opened 2016-09-12 21:34 UTC
I would like to change exception handling in the core algorithm. Currently any exception in the KB search halt the algorithm execution.

I would like to change it so that the exception would only cause to skip the value disambiguation.

**Comment by brodecva** [comment] 2016-09-12 21:42
> I would like to change it so that the exception would only cause to skip the value disambiguation.

@JanVana Grate! This bugged me to. But keep in mind that the user must be aware which cells (columns, relations) were skipped in processing due to regular reasons (e.g. no appropriate concept found) and which were skipped due to unexpected processing error. This information must be delivered in a transparent way to a potential client.

Unless the TAnnotation somehow supports this, propose some transparent extension of the result format that solves this requirement.

**Comment by JanVana** [comment] 2016-09-12 21:51
I was thinking of simply adding a boolean flag to cell disambiguation. Any exceptions would be caught and logged at the KB search level.

**Comment by brodecva** [comment] 2016-09-12 21:58
>I was thinking of simply adding a boolean flag to cell disambiguation. Any exceptions would be caught and logged at the KB search level.

OK. A flag might suffice.

**Comment by tomas-knap** [comment] 2016-09-20 09:30
Yes, but please have a reasonable warning in the logs

**Comment by tomas-knap** [comment] 2016-11-27 15:49
Please look on that in iteration 4 (as this is easy, but may make it more robust) - probably JanVana may look into that, @brodecva please decide.  Lower prio.

**Comment by brodecva** [comment] 2016-12-28 01:50
@josef-janousek May go nicely with #262 .

**Comment by brodecva** [comment] 2017-01-04 14:29
@JanVana Consider solving it together with #248 .

**Comment by brodecva** [comment] 2017-01-06 12:34
Add logging of the search request, especially failed one.

**Comment by brodecva** [comment] 2017-01-13 09:37
To recapitulate: non-fatal exception in the middle of processing should not abort the processing. They should be recorded somehow, and in the end provided to the user in the warnings field (so far this is a list of strings, but you can extend it to a more complex structure) of the Result class.

**Comment by tomas-knap** [comment] 2017-02-03 13:08
Extend result from tableMiner. Discuss with @brodecva if needed

**Comment by tomas-knap** [comment] 2017-02-08 08:31
@JanVana Please let me know in the evening how it goes

**Comment by JanVana** [comment] 2017-02-10 07:32
I apologize for the delay. The task took longed than I expected. It is implemented in the pull request #369.

**Comment by brodecva** [comment] 2017-02-10 08:23
@JanVana Thanks! I have tested it for the case of HTTP connection drop out and it worked.

**Comment by tomas-knap** [comment] 2017-02-15 09:23
Does not work? See: https://github.com/odalic/sti/issues/372

**Comment by tomas-knap** [comment] 2017-02-15 10:23
Closing for now as #372 cannot be reproduced

**Closed by tomas-knap** 2017-02-15 10:23 UTC
Labels: core, enhancement, knowledge bases, priority: High
