### ISSUE TITLE
When exporting RDF (turtle), it opens in google excel spreadsheet

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#457] opened 2017-05-30 08:36 UTC
This worked before, but now it does not work: 

![screen shot 2017-05-30 at 10 35 42](https://cloud.githubusercontent.com/assets/3014917/26575005/da90b4d4-4523-11e7-9de4-a1e2d21b959b.png)

**Comment by tomas-knap** [comment] 2017-05-30 08:37
The same issue for JSON-LD and Annotations

**Comment by brodecva** [comment] 2017-05-30 08:56
Duplicate of https://github.com/odalic/odalic-ui/issues/437 .

**Closed** 2017-05-30 08:57 UTC
Labels: bug, duplicate, priority: High
