### ISSUE TITLE
Export to Turtle/JSON-LD does not work after re-execute

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#290] opened 2017-01-06 11:13 UTC
Steps to reproduce:
1) Run Odalic on top of [Books-v1.csv](https://github.com/odalic/sti/files/689725/Books-v1.csv.2.zip)

2) propose new classification for series, use that
3) re-execute
4) try to export, nothing is displayed.

**Comment by brodecva** [comment] 2017-01-06 18:16
Hi, @josef-janousek . The exceptions should not be swalloved now. You can look at it.

**Comment by josef-janousek** [comment] 2017-01-06 23:30
@tomas-knap , @brodecva : This fault was caused by invalid URI (without prefix part) which was sent by client UI after proposal. Now I added checks for this situation to the RDF export adapter. So when the IRI is not valid, no triple is produced and error message is written to the log, but the whole process of exporting is not interrupted. Maybe another question could be, if we eventually should inform the user about the occurence of invalid IRI more than just in the log.

**Comment by brodecva** [comment] 2017-01-07 14:17
@josef-janousek I have accepted your fix. But it only hides the problem, which is: why does the newly proposed class have only the suffix loaded when processed? I suspect that this might be caused by the proposal, and not necessarily by the export or even processing, but could you please help @JanVana by investigating the cause first?

Otherwise this problem is still not fixed, because the accepted pull request would result in the proposed class not appearing in the exported result.

**Comment by brodecva** [comment] 2017-01-07 14:49
> @josef-janousek I have accepted your fix. But it only hides the problem, which is: why does the newly proposed class have only the suffix loaded when processed? I suspect that this might be caused by the proposal, and not necessarily by the export or even algorithm processing, but could you please help @JanVana by investigating the cause first?
>
> Otherwise this problem is still not fixed, because the accepted pull request would result in the proposed class not appearing in the exported result.

So @josef-janousek reminded me about the discussion from the recet meeting, that this is caused by the client, which send incomplete URI in the feedback.

I will close this one, but may create a separate task that would deal with the fact, that the server without protests accepts this flawed feedback.

**Closed** 2017-01-07 14:49 UTC
Labels: bug, core, extension, in progress, java, priority: Urgent

**Comment by tomas-knap** [comment] 2017-01-09 10:06
Relates with: https://github.com/odalic/odalic-ui/issues/248. 
May relate also with: https://github.com/odalic/odalic-ui/issues/240
