### ISSUE TITLE
Search under German DBpedia returns no results

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#284] opened 2017-01-05 11:32 UTC
This is important. Please try to fix it ASAP.

**Comment by brodecva** [comment] 2017-01-05 11:37
I have noticed, that you have changed the configs. I will update them and then check if the problem remains.

**Comment by brodecva** [comment] 2017-01-05 12:26
@JanVana Unfortunately the problem remains. But I have narrowed it: it only fails for classes for some reason.

**Comment by brodecva** [comment] 2017-01-10 14:20
@JanVana Any progress? Still waiting for your report.

**Comment by JanVana** [comment] 2017-01-11 05:12
I have made some changes in the configuration files of german DBpedia, but this problem will be difficult to fix. The main issue is, that most classes in this KB have no properties. As a result, they will never be found, because KBProxy searches for classes by label.

I have tried an approach with searching classes using their ULR links, but it was very slow and it didn't work very well. I would welcome any suggestion about how to approach this problem.

**Comment by tomas-knap** [comment] 2017-01-11 10:13
What could work is to take just the URL suffix, not the whole URL. But that is strange, I would expect that rdf:label (at least) is there, right?

**Comment by JanVana** [comment] 2017-01-11 12:10
There are literally no properties on most types in german DBpedia. As an example try searching types of Steven Erikson:

```
SELECT DISTINCT ?Type
{
  <http://de.dbpedia.org/resource/Steven_Erikson> a ?Type
}
```

Now try selecting properties of these types, like:
```
select distinct ?Predicate ?Object where
{
  <http://xmlns.com/foaf/0.1/Person> ?Predicate ?Object
}
```
or
```
select distinct ?Predicate ?Object where
{
  <http://schema.org/Person> ?Predicate ?Object
}
```
or
```
select distinct ?Predicate ?Object where
{
  <http://dbpedia.org/ontology/Person> ?Predicate ?Object
}
```

**Comment by brodecva** [comment] 2017-01-11 12:11
> I have made some changes in the configuration files of german DBpedia, but this problem will be difficult to fix. The main issue is, that most classes in this KB have no properties. As a result, they will never be found, because KBProxy searches for classes by label.
>
>I have tried an approach with searching classes using their ULR links, but it was very slow and it didn't work very well. I would welcome any suggestion about how to approach this problem.

@JanVana This is interesting. How is it possible that the initial run of algorithm succeeds in assigning of the correct resources in the German DBpedia to CSV cell and header contents? My impression was that it uses the labels as well...

**Comment by JanVana** [comment] 2017-01-11 12:23
The algorithm uses labels only for disambiguation. Classification only needs some types assigned to the cell value. The types themselves don't need any additional properties. The algorithm examines their labels, but can fall back on parsing url when no proper label is available.

**Comment by brodecva** [comment] 2017-01-11 12:49
> The algorithm uses labels only for disambiguation. Classification only needs some types assigned to the cell value. The types themselves don't need any additional properties. The algorithm examines their labels, but can fall back on parsing url when no proper label is available.

Thanks for clearing that up.

**Comment by brodecva** [comment] 2017-01-11 12:56
> There are literally no properties on most types in german DBpedia.

@tomas-knap What shall we do about it (in the later iterations)? The first thing that comes to my mind is to somehow switch for these language-agnostic entitites to the English DBpedia... But this a bit dirty solution. Or can we make contact with the administrator of the German DBpedia, and ask them to fix the affected resources?

> What could work is to take just the URL suffix, not the whole URL.

@JanVana Would this imprtove the situation, as @tomas-knap suggests?

**Comment by JanVana** [comment] 2017-01-11 16:19
@brodecva @tomas-knap I have already tried searching in the URL. There are two main issues with this approach.

1) It is very slow. These URL values are not in the full-text catalog of Virtuoso, so you have to use regex filter.
2) You get duplicate results. One result found through label and one through URL match.

I will continue to work on the URL approach for now and test if using the URL suffix will speed things up.

Thanks for suggestions.

**Comment by tomas-knap** [comment] 2017-01-12 08:31
This is a bit connected with https://github.com/odalic/sti/issues/312 

In usual case, if the ontology provides its own classes, there should be also e.g. label and further description for that class. If not, it is not correct. For external classes (external URLs), typically there is no further info. 

So in general, the problem is that the class may appear in the classification (because there is another type which has class associated), but they are not searchable. 

There are some options suggested at: https://github.com/odalic/sti/issues/312

We can ask the guys but they re-generate dbpedia content from time to time, so I am a bit sceptic about timing. 

Parsing URL and taking suffix is not that nice and also there are performance penalties. 
For now, I would suggest to not search in URL and simply do not try to find a workaround for that.

**Comment by tomas-knap** [comment] 2017-01-12 08:31
So I would suggest to close as wont' fix (it is rather an issue of the KB)

**Comment by tomas-knap** [comment] 2017-01-12 08:33
In terms of https://github.com/odalic/sti/pull/310/ trying to fix that, I would suggest to revert the commits adding support for searching in the URIs - so not to use info from URIs. URIs are identifiers, which does not necessary should contain the label - so in many cases it will anyway not work.

**Closed** 2017-01-12 18:07 UTC
Labels: bug, in progress, knowledge bases, priority: Urgent, sparql, wontfix
